name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        run: |
          echo "ğŸš€ Starting repository checkout..."
        
      - uses: actions/checkout@v4
      
      - name: Verify Checkout
        run: |
          echo "âœ… Repository checkout completed"
          echo "âœ… Docker compose file found"
          
      - name: Deploy with Docker Compose and Verify
        env:
          PORT: ${{ secrets.PORT }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          echo "ğŸš€ Starting Docker deployment..."
          if ! cd backend && sudo docker-compose up --build --wait -d; then
            echo "âŒ Docker deployment failed"
            echo "Container logs:"
            docker-compose logs
            exit 1
          fi
          echo "âœ… Docker deployment completed successfully"
          
      - name: Show Docker Logs on Failure
        if: always()
        run: |
          echo "showing logs"
          cd backend && sudo docker-compose logs
          
      - name: Prune Old Docker Images
        if: success()
        run: |
          echo "ğŸš€ Starting image cleanup..."
          sudo docker image prune -a -f
          echo "âœ… Image cleanup completed"
