name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        run: |
          echo "üöÄ Starting repository checkout..."
        
      - uses: actions/checkout@v4
      
      - name: Verify Checkout
        run: |
          echo "‚úÖ Repository checkout completed"
          echo "‚úÖ Docker compose file found"
          
      - name: Deploy with Docker Compose and Verify
        env:
          PORT: ${{ secrets.PORT }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          echo "üöÄ Starting Docker deployment..."
          cd backend
          if ! sudo docker-compose up --build -d; then
            echo "‚ùå Docker deployment failed"
            echo "Container logs:"
            docker-compose logs
            exit 1
          fi
          echo "‚úÖ Docker deployment completed successfully"
          

      - name: Show Docker Logs
        if: always()
        run: |
          echo "showing logs for app"
          cd backend && sudo docker-compose logs app
          echo "showing logs for docker"
          cd backend && sudo docker-compose logs redis
          
      - name: Prune Old Docker Images
        if: success()
        run: |
          echo "üöÄ Starting image cleanup..."
          sudo docker image prune -a -f
          echo "‚úÖ Image cleanup completed"
